services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5700:5700"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8091:8091"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi.py
      - DATABASE_URL=sqlite:///instance/memberlist.db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge