version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5200:5200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://checkin.bkauto.vn/
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=wsgi.py
      - DATABASE_URL=sqlite:///app.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge